/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Beavr": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POLAR_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POLAR_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UPSTASH_REDIS_REST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UPSTASH_REDIS_REST_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}