import type { Metadata } from "next";
import { Carme, Aleo, IBM_Plex_Mono } from 'next/font/google';
import "./globals.css";
import { Providers } from "@/lib/providers";


const fontSans = Carme({ weight: '400', subsets: ['latin'], variable: '--font-sans' });
const fontSerif = Aleo({ subsets: ['latin'], variable: '--font-serif' });
const fontMono = IBM_Plex_Mono({ weight: ['100', '400', '700'], subsets: ['latin'], variable: '--font-mono' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
      <body className="font-sans antialiased">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
